// Generated by https://quicktype.io
/* fijate que la puta extensión requiere tener JSON en el portapapeles */
export interface PokemonListResponse {
  count:    number;
  next?:     string;
  previous?: string;
  results:  SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  url:  string;
  id: number;
  img: string;
}
